
[functions.send-email]
enabled = true
verify_jwt = false
import_map = "./functions/send-email/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-email/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-email/*.html" ]

[functions.send-trainer-email]
enabled = true
verify_jwt = false
entrypoint = "./functions/send-trainer-email/index.ts"

[functions.send-certificate-email]
enabled = true
verify_jwt = true
entrypoint = "./functions/send-certificate-email/index.ts"

[functions.generate-certificate-test]
enabled = true
verify_jwt = true
entrypoint = "./functions/generate-certificate-test/index.ts"

[functions.send-assignment-notifications]
enabled = true
verify_jwt = true
entrypoint = "./functions/send-assignment-notifications/index.ts"

[functions.submit-student-registration]
enabled = true
verify_jwt = false
entrypoint = "./functions/submit-student-registration/index.ts"

[functions.approve-student-registration]
enabled = true
verify_jwt = true
entrypoint = "./functions/approve-student-registration/index.ts"

[functions.save-student-mapping]
enabled = true
verify_jwt = true
entrypoint = "./functions/save-student-mapping/index.ts"
